{% set python_min = '3.11' %}
{% set name = "dyson-equalizer" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dyson_equalizer-{{ version }}.tar.gz
  sha256: 7eb9c48f7d45d12b0313fb931801c9a34cbec3ec0ca778eb9bdd89b36e9c46c0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core
    - flit-scm
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.6
    - numpy >=1.25
    - scipy >=1.13

test:
  imports:
    - dyson_equalizer
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/KlugerLab/DysonEqualizer
  summary: Computes the Dyson Equalizer and related low rank approximation of the input data
  license: MIT
  license_file: LICENSE
  doc_url: https://klugerlab.github.io/DysonEqualizer/
  dev_url: https://github.com/KlugerLab/DysonEqualizer

extra:
  recipe-maintainers:
    - fra-pcmgf
